language: cpp
sudo: true
dist: trusty
addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev

compiler:
    - g++

#Build steps
install:
    - git clone https://github.com/ptitSeb/SDL_sound
    - cd SDL_sound
    - ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - sudo make install
    - cd ..

script:
    - cmake .
    - make
