language: cpp
sudo: true
dist: trusty

compiler:
    - g++

#Build steps
before_install:
    - sudo apt-get install libsdl2-dev libsdl2-image-dev -y
    - git clone https://github.com/ptitSeb/SDL_sound
    - cd SDL_sound
    - ./autogen.sh
    - ./configure
    - make
    - sudo make install
    - cd ..

script:
    - cmake .
    - make
